services:
  db:
    image: pgvector/pgvector:pg16
    container_name: repomind-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: repomind
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  pgadmin:
    image: dpage/pgadmin4
    container_name: repomind-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@repomind.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  ai-engine:
    build:
      context: ./services/ai-engine
      dockerfile: Dockerfile
    container_name: repomind-ai-engine
    restart: always
    gpus: all
    environment:
      LLM_MODEL_NAME: sshleifer/tiny-gpt2
      LLM_DEVICE: ${LLM_DEVICE:-cpu}
      EMBEDDING_MODEL_NAME: sentence-transformers/all-MiniLM-L6-v2
      EMBEDDING_DEVICE: ${EMBEDDING_DEVICE:-cpu}
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      HF_HUB_VERBOSITY: "debug"
    ports:
      - "50051:50051"
    volumes:
      - hf_cache:/root/.cache/huggingface

  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    container_name: repomind-orchestrator
    restart: always
    environment:
      APP_ADDRESS: 0.0.0.0
      APP_PORT: 3001
      DATABASE_URL: postgres://user:password@db:5432/repomind?sslmode=disable
      AI_ENGINE_URL: ai-engine:50051
      GITHUB_TOKEN: dev-local-token
      MAX_WORKERS: 3
    ports:
      - "3001:3001"
    depends_on:
      - db
      - ai-engine

volumes:
  pgdata:
  hf_cache: