// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/ai_service.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EMBEDDINGS MESSAGES
type EmbeddingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         []string               `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingRequest) Reset() {
	*x = EmbeddingRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingRequest) ProtoMessage() {}

func (x *EmbeddingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingRequest.ProtoReflect.Descriptor instead.
func (*EmbeddingRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingRequest) GetTexts() []string {
	if x != nil {
		return x.Texts
	}
	return nil
}

type EmbeddingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Embeddings    []*Vector              `protobuf:"bytes,1,rep,name=embeddings,proto3" json:"embeddings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResponse) Reset() {
	*x = EmbeddingResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResponse) ProtoMessage() {}

func (x *EmbeddingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResponse.ProtoReflect.Descriptor instead.
func (*EmbeddingResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *EmbeddingResponse) GetEmbeddings() []*Vector {
	if x != nil {
		return x.Embeddings
	}
	return nil
}

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_proto_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

// LLM MESSAGES
type CompletionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*Message             `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionRequest) Reset() {
	*x = CompletionRequest{}
	mi := &file_proto_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionRequest) ProtoMessage() {}

func (x *CompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionRequest.ProtoReflect.Descriptor instead.
func (*CompletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *CompletionRequest) GetHistory() []*Message {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *CompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *CompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

type CompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompletionResponse) Reset() {
	*x = CompletionResponse{}
	mi := &file_proto_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompletionResponse) ProtoMessage() {}

func (x *CompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompletionResponse.ProtoReflect.Descriptor instead.
func (*CompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *CompletionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

var File_proto_ai_service_proto protoreflect.FileDescriptor

const file_proto_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ai_service.proto\x12\taiservice\"(\n" +
	"\x10EmbeddingRequest\x12\x14\n" +
	"\x05texts\x18\x01 \x03(\tR\x05texts\"F\n" +
	"\x11EmbeddingResponse\x121\n" +
	"\n" +
	"embeddings\x18\x01 \x03(\v2\x11.aiservice.VectorR\n" +
	"embeddings\" \n" +
	"\x06Vector\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\"\x82\x01\n" +
	"\x11CompletionRequest\x12,\n" +
	"\ahistory\x18\x01 \x03(\v2\x12.aiservice.MessageR\ahistory\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\x05R\tmaxTokens\"(\n" +
	"\x12CompletionResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"7\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent2c\n" +
	"\x10EmbeddingService\x12O\n" +
	"\x12GenerateEmbeddings\x12\x1b.aiservice.EmbeddingRequest\x1a\x1c.aiservice.EmbeddingResponse2_\n" +
	"\n" +
	"LLMService\x12Q\n" +
	"\x12GenerateCompletion\x12\x1c.aiservice.CompletionRequest\x1a\x1d.aiservice.CompletionResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_ai_service_proto_rawDescOnce sync.Once
	file_proto_ai_service_proto_rawDescData []byte
)

func file_proto_ai_service_proto_rawDescGZIP() []byte {
	file_proto_ai_service_proto_rawDescOnce.Do(func() {
		file_proto_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)))
	})
	return file_proto_ai_service_proto_rawDescData
}

var file_proto_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_ai_service_proto_goTypes = []any{
	(*EmbeddingRequest)(nil),   // 0: aiservice.EmbeddingRequest
	(*EmbeddingResponse)(nil),  // 1: aiservice.EmbeddingResponse
	(*Vector)(nil),             // 2: aiservice.Vector
	(*CompletionRequest)(nil),  // 3: aiservice.CompletionRequest
	(*CompletionResponse)(nil), // 4: aiservice.CompletionResponse
	(*Message)(nil),            // 5: aiservice.Message
}
var file_proto_ai_service_proto_depIdxs = []int32{
	2, // 0: aiservice.EmbeddingResponse.embeddings:type_name -> aiservice.Vector
	5, // 1: aiservice.CompletionRequest.history:type_name -> aiservice.Message
	0, // 2: aiservice.EmbeddingService.GenerateEmbeddings:input_type -> aiservice.EmbeddingRequest
	3, // 3: aiservice.LLMService.GenerateCompletion:input_type -> aiservice.CompletionRequest
	1, // 4: aiservice.EmbeddingService.GenerateEmbeddings:output_type -> aiservice.EmbeddingResponse
	4, // 5: aiservice.LLMService.GenerateCompletion:output_type -> aiservice.CompletionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ai_service_proto_init() }
func file_proto_ai_service_proto_init() {
	if File_proto_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_service_proto_rawDesc), len(file_proto_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_ai_service_proto_goTypes,
		DependencyIndexes: file_proto_ai_service_proto_depIdxs,
		MessageInfos:      file_proto_ai_service_proto_msgTypes,
	}.Build()
	File_proto_ai_service_proto = out.File
	file_proto_ai_service_proto_goTypes = nil
	file_proto_ai_service_proto_depIdxs = nil
}
