# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/ai_service.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'proto/ai_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/ai_service.proto\x12\taiservice\"!\n\x10\x45mbeddingRequest\x12\r\n\x05texts\x18\x01 \x03(\t\":\n\x11\x45mbeddingResponse\x12%\n\nembeddings\x18\x01 \x03(\x0b\x32\x11.aiservice.Vector\"\x18\n\x06Vector\x12\x0e\n\x06values\x18\x01 \x03(\x02\"a\n\x11\x43ompletionRequest\x12#\n\x07history\x18\x01 \x03(\x0b\x32\x12.aiservice.Message\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\"\"\n\x12\x43ompletionResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2c\n\x10\x45mbeddingService\x12O\n\x12GenerateEmbeddings\x12\x1b.aiservice.EmbeddingRequest\x1a\x1c.aiservice.EmbeddingResponse2_\n\nLLMService\x12Q\n\x12GenerateCompletion\x12\x1c.aiservice.CompletionRequest\x1a\x1d.aiservice.CompletionResponseB\tZ\x07./protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ai_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\007./proto'
  _globals['_EMBEDDINGREQUEST']._serialized_start=37
  _globals['_EMBEDDINGREQUEST']._serialized_end=70
  _globals['_EMBEDDINGRESPONSE']._serialized_start=72
  _globals['_EMBEDDINGRESPONSE']._serialized_end=130
  _globals['_VECTOR']._serialized_start=132
  _globals['_VECTOR']._serialized_end=156
  _globals['_COMPLETIONREQUEST']._serialized_start=158
  _globals['_COMPLETIONREQUEST']._serialized_end=255
  _globals['_COMPLETIONRESPONSE']._serialized_start=257
  _globals['_COMPLETIONRESPONSE']._serialized_end=291
  _globals['_MESSAGE']._serialized_start=293
  _globals['_MESSAGE']._serialized_end=333
  _globals['_EMBEDDINGSERVICE']._serialized_start=335
  _globals['_EMBEDDINGSERVICE']._serialized_end=434
  _globals['_LLMSERVICE']._serialized_start=436
  _globals['_LLMSERVICE']._serialized_end=531
# @@protoc_insertion_point(module_scope)
